[package]
name = "protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
compact_str = { version = "0.4", default-features = false, features = [ "serde" ] }
serde = { version = "1", default-features = false, features = [ "derive", "alloc", "rc" ] }
